### PR TITLE
First draft of collaboration episode

### LINKED ISSUE #5: Draft episode content for `collaboration.md`
- [ ] reading list
    - a list of pages/publications trainees should read before joining this group discussion.
- [ ] discussion questions
    - questions to prompt interesting and relevant discussion around the themes of the week's reading.
    - it is totally fine - perhaps better, even - if these are questions that we do not have an answer to, e.g. the discussions could be useful for informing and improving the CLDT curriculum. It will probably make them more interesting too!
- [ ] (optional) homework task(s)
    - anything you think it could be helpful for trainees to work through on their own between group discussions
    - we should certainly not aim to have homework every week, especially where the reading list for next week is already long.

### PR DESCRIPTION
**Pull request by sstevens2**
Closes #5 

First draft of the collaboration episode. I decided to keep the text minimal but let me know if we think it should have more explanatory text.

### CODE REVIEW

**Comment by sstevens2** [comment]
Closes #5

**Comment by tobyhodges** [comment]
@sstevens2 I feel the list of discussion questions that I drafted is quite heavily weighted towards the decision-making section of the curriculum, and perhaps neglects the other aspects of collaboration that we also teach. Do you have any suggestions for other questions we could ask to prompt a broader discussion among Trainers? E.g. something about collaborative practices that have succeeded (or not succeeded) for them in the past; or about the tools and approaches they take to manage their own projects?

**Comment by sstevens2** [comment]
I added a question about strategies for collaborating. I welcome additional questions or changes to the discussion questions.

**Review by tobyhodges — APPROVED** [review]
Thank you @sstevens2 I like the way you phrased the additional questions.

**Pull request merged**
